[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/content/*"
  to = "/content/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
